"""empty message

Revision ID: 96bfe2e0949f
Revises: 68ba9134e6d2
Create Date: 2026-01-14 09:43:35.334162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96bfe2e0949f'
down_revision = '68ba9134e6d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consola_videojuego',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consola_id', sa.Integer(), nullable=False),
    sa.Column('videojuego_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['consola_id'], ['consola.id'], ),
    sa.ForeignKeyConstraint(['videojuego_id'], ['videojuego.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consola_videojuego')
    # ### end Alembic commands ###
